### ISSUE TITLE
2023-06-05 초안결정 회의

### ISSUE THREAD

**Issue by jakebae87** [jakebae87/119#1]
쇼핑몰 웹페이지의 카테고리(로그인, 장바구니, 품목리스트 페이지) 자료조사를 바탕으로 초안 작성 및 회의

**Comment by jakebae87** [comment]
5월31일 회의를 통해 결정된 주제와 쇼핑몰 이름을 바탕으로 카테고리 선택 및 초안 작성을 위한 회의입니다.

- WireFrame 제작 참고 사이트 (https://app.moqups.com/MtWtJ1PpnE7OJ3t3tNtswWufRLnEgHlI/edit/page/aef4b8283)
- [배정현_와이어프레임.pptx](https://github.com/jakebae87/119/files/11637251/_.pptx)

**Comment by emperor5519** [comment]
**[내용]**
   
- 쇼핑몰 UI의 body 초안 결정
1. 기본적으로 PETHROOM 사이트의 UI를 많이 참고.
2. body의 상단부터, 프로모션 상품 - NEW 상품 - BEST 상품 순으로 배치하고, 각각 자동으로 다음 상품으로 넘어가도록 제작.
3. NEW 상품 및 BEST 상품 부분은 한번에 3개의 상품이 보이도록 하고, 더보기 버튼을 통해, 각각 NEW 상품 페이지와 BEST 상품 페이지로 이동.   


- 커뮤니티 카테고리 관련
1. 기존 와이어프레임 ppt의 커뮤니티 페이지 UI 이용.   


- 상품 카테고리 관련
1. 별개의 페이지로 이동하는 NEW / BEST /강아지 / 고양이 버튼과, 사료 간식 등의 각종 용품 버튼들로 구성됨.
2. NEW / BEST /강아지 / 고양이 페이지는 사료, 간식 등의 분류 없이, 바로 상품들이 나열됨.
3. 그 외의 버튼들은 ALL 상품 카테고리 아래서, 각 용품별로 분류되어 구성됨.   


**[해야할 일]**

- 인원별 제작 진행할 기능 및 페이지 역할분담.
- 깃허브 및 소스트리 사용법 숙지


**[다음 회의일정]**

-

**Comment by jakebae87** [comment]
> [일시]
> 
> * 6월 5일 월요일
> 
> [내용]
> 
> * 6월 4일 일요일 회의 내용 기반으로 초안 결정
> 
> [해야할 일]
> 
> * 초안 결정완료 및 스케치
> * 페이지별 와이어 프레임 작성 (https://app.moqups.com/)
